FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "NetHostBeef"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/nethost/runtimes/win-x64/native/nethost.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/nethost/runtimes/win-x64/native/*.dll\")"]
